theme: jekyll-theme-cayman
show_downloads: true
markdown: kramdown
title: Revents - Reactor based CQRS / Event Sourcing framework
baseurl: "/revents"
github:
  zip_url: https://github.com/szjani/revents/archive/master.zip
  tar_url: https://github.com/szjani/revents/archive/master.tar.gz