theme: jekyll-theme-cayman
show_downloads: true
markdown: kramdown
github:
  zip_url: https://github.com/szjani/revents/archive/master.zip
  tar_url: https://github.com/szjani/revents/archive/master.tar.gz